PayrollManagement/Controllers/SalaryController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PayrollManagement.Models;
using System.Data;
using  PayrollManagement.EfData;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using iTextSharp ;
using iTextSharp.text;
using iTextSharp.text.pdf;

using Microsoft.EntityFrameworkCore.SqlServer;

namespace PayrollManagement.Controllers;

public class SalaryController : Controller
{
    private readonly PaymentDbContext _paymentDb;
    public SalaryController(PaymentDbContext database)
    {
        DatabaseConnection.connectDatabase();
        _paymentDb = database;
    }
    public IActionResult manageSalary(int EmpID){
        ViewBag.status = HttpContext.Session.GetString("status");
        ViewBag.username = HttpContext.Session.GetString("username");
        ViewBag.usermode = HttpContext.Session.GetString("usermode");
        ViewBag.employeeID = Convert.ToString(EmpID);
        HttpContext.Session.SetString("EmployeeID",Convert.ToString(EmpID));
        ViewBag.department = DatabaseConnection.getDepartment(EmpID);
        var status=_paymentDb.PaymentManagement.Where(payment=>payment.EmployeeID == EmpID ).ToList();
        
       foreach(var item in status)
       {
           if(item.Status=="permanent")
           {
               return View("payBonusAndDues");
           }
       }
      
        return View("manageSalary");
    }

    [HttpPost]
    public IActionResult manageSalary(Salary payment){
        ViewBag.status = HttpContext.Session.GetString("status");
        ViewBag.username = HttpContext.Session.GetString("username");
        ViewBag.usermode = HttpContext.Session.GetString("usermode");
        payment.Status= "temporary";
        _paymentDb.PaymentManagement.Add(payment);
        _paymentDb.SaveChanges();

        payment.Status = "permanent";
        _paymentDb.PaymentManagement.Update(payment);
        _paymentDb.SaveChanges();
       
        IEnumerable<Salary> employeeList = _paymentDb.PaymentManagement;
        
     
        Console.WriteLine("inserted successfully");
        return View("paymentData",employeeList);
  
    }
    //group payment depends on department
    public IActionResult payInBulk(){
        ViewBag.status = HttpContext.Session.GetString("status");
        ViewBag.username = HttpContext.Session.GetString("username");
        ViewBag.usermode = HttpContext.Session.GetString("usermode");
        
        return View();
    }
    [HttpPost]
    public IActionResult payInBulk(BulkPay bulkPay){
        ViewBag.status = HttpContext.Session.GetString("status");
        ViewBag.username = HttpContext.Session.GetString("username");
        ViewBag.usermode = HttpContext.Session.GetString("usermode");
        // String result = DatabaseConnection.payBulk(bulkPay);
        
        List<Salary> employee=_paymentDb.PaymentManagement.Where(department=>department.Department==bulkPay.Department).ToList();
         foreach(var item in employee)
         {
             
             item.CreditAmount=bulkPay.Amount;
             item.TotalEarnings+=bulkPay.Amount;
             _paymentDb.PaymentManagement.Update(item);
             _paymentDb.SaveChanges();
         }
        IEnumerable<Salary> employeeList = _paymentDb.PaymentManagement;
        return View("paymentData",employeeList);

    }
    [HttpGet]
    public IActionResult payBonusAndDues(){
        ViewBag.EmployeeID = HttpContext.Session.GetString("EmployeeID");
        ViewBag.status = HttpContext.Session.GetString("status");
        ViewBag.username = HttpContext.Session.GetString("username");
        ViewBag.usermode = HttpContext.Session.GetString("usermode");
        return View();
    }
    [HttpPost]
    public IActionResult payBonusAndDues(Salary salary){
        Console.WriteLine(salary.EmployeeID);
        ViewBag.status = HttpContext.Session.GetString("status");
        ViewBag.username = HttpContext.Session.GetString("username");
        ViewBag.usermode = HttpContext.Session.GetString("usermode");

        List<Salary> employee = _paymentDb.PaymentManagement.Where(employee => employee.EmployeeID==salary.EmployeeID).ToList();
        Console.WriteLine(employee.Count);
        foreach(var item in employee){
            item.Bonus += salary.Bonus;
            item.Dues += salary.Dues;
            item.TotalEarnings += salary.Bonus;
            item.TotalEarnings -= salary.Dues;
            _paymentDb.PaymentManagement.Update(item);
            _paymentDb.SaveChanges();
        }
        
         IEnumerable<Salary> employeeList = _paymentDb.PaymentManagement;
        
     
        
        return View("paymentData",employeeList);

    }
    public IActionResult paymentData(){
        ViewBag.status = HttpContext.Session.GetString("status");
        ViewBag.username = HttpContext.Session.GetString("username");
        ViewBag.usermode = HttpContext.Session.GetString("usermode");
        
        IEnumerable<Salary> employeeList = _paymentDb.PaymentManagement;
        Console.WriteLine("Payment Data feteched");
        return View(employeeList);
     
    }
      
    


}

PayrollManagement/Views/Admin/index.cshtml
@{
    ViewData["Title"] = "Admin Page";
    Layout = "_Layout";
}



<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Payroll management</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    @* font-awesome *@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @* google icon *@
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body >
  
    <div class="pt-1 jumbotron jumbotron-text  text-black  admin-header" style="font-size:2em">
      welcome @ViewBag.username 
      <h5>@TempData["Time"]</h5>
    </div>
    <div class="card-container">
      @{
        if(@ViewBag.usermode == "Admin"){
            <!-- <div class="admin-cards">
            <div >
              <i class="material-icons " style="font-size:10em">assignment</i>
            </div>
            <div>
              <a asp-controller="Admin" asp-action="registration">
                <button class="button">Enroll</button>
              </a>
            </div>
          </div> -->
          <div class="admin-cards">
            <div>
              <span class="material-symbols-rounded "  style="font-size:9em">
                <i class="fa fa-search" aria-hidden="true"></i>
              </span>
            </div>
            <div>
              <a asp-controller="Admin" asp-action="viewEmployee">
                <button class="button">View</button>
              </a>
            </div>
          </div>
          <div class="admin-cards">
            <div style="margin-top:-0.7em;margin-bottom:0.7em">
              <span style="font-size:7em; ">
                <img src="../image/addUser.png" />
              </span>
            </div>
            <div>
              <a asp-controller="Admin" asp-action="registration">
                <button class="button">Add User</button>
              </a>
            </div>
          </div>
           <div class="admin-cards">          
                <img src="../image/payBulk.png" height="175px" width="150px"/>          
            <div>
              <a asp-controller="Salary" asp-action="payInBulk">
                <button class="button">pay Bulk</button>
              </a>
            </div>
          </div>
          <div class="admin-cards">          
                <img src="../image/admin.png" height="150px" width="150px"/>          
            <div>
              <a asp-controller="Admin" asp-action="viewAdmin">
                <button class="button">Admins</button>
              </a>
            </div>
          </div>

        }
      }
      
    </div>
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

PayrollManagement/Views/Admin/registration.cshtml
@model Employee
@{
    
    Layout = "_Layout";
    ViewData["Title"] = "Registration";
}
<head>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    -->

</head>
<body>
    <div class="container card">
        
        <div>
            <h1>Register</h1>
        </div>
        @{
            if(@ViewBag.status == "Exist"){
                <div class="alert alert-danger alert-dismissible">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>Alert!</strong>ID already exist.
                </div>
            }
        }
        
        
        <form method="post" class="form-container" enctype="multipart/form-data">
            <div class="mb-3 mt-3">
                
                <input asp-for="EmployeeID"  type="number" name="EmployeeID"class="form-control" placeholder="Employee ID" required/>
                
            </div>   

            <div class="mb-3">
                
                <input asp-for="EmployeeName" type="text" name="EmployeeName" pattern="^[A-Za-z]+$" Title="only texts are allowed" class="form-control" placeholder="Employee name" required/>
                @Html.ValidationMessageFor((data => data.EmployeeName),"",new{@class ="text-danger"})
            </div> 

            <div class="mb-3">
                <input asp-for="Age" type="number" name="Age" class="form-control" placeholder="Employee age" required/>
                @Html.ValidationMessageFor((data => data.Age),"",new{@class ="text-danger"})
            </div> 

            <div class="mb-3">
                <input asp-for="Salary" type="number" name="Salary" class="form-control" placeholder="Employee salary" required/>
                @Html.ValidationMessageFor((data => data.Salary),"",new{@class ="text-danger"})
            </div> 
            <div>
                <p>Please select your department:</p>
                <input type="radio" id="Development" name="Department" value="Development">
                <label for="Development">Development</label><br>
                <input type="radio" id="Research" name="Department" value="Research">
                <label for="Research">Research</label><br>  
                <input type="radio" id="Testing" name="Department" value="Testing">
                <label for="Testing">Testing</label><br><br>
                @Html.ValidationMessageFor((data => data.Department),"",new{@class ="text-danger"})
            </div>
            
            <div class="mb-3 mt-3">
                <input asp-for="MailId" type="text" name="MailId" class="form-control" placeholder="Enter mail id" required/>
                 @Html.ValidationMessageFor((data => data.MailId),"",new{@class ="text-danger"})
            </div>
            <div class="mb-3">
                <input asp-for="PhoneNumber" type="PhoneNumber" name="PhoneNumber" class="form-control" placeholder="Phone number" required/>
                @Html.ValidationMessageFor((data => data.PhoneNumber),"",new{@class ="text-danger"})
            </div> 
            <div class="mb-3">
                <input asp-for="Password" type="password" name="Password" class="form-control" placeholder="Password" required/>
                 @Html.ValidationMessageFor((data => data.Password),"",new{@class ="text-danger"})
            </div> 
           
            <div>
                <p>Please select user mode:</p>
                <input type="radio" id="Admin" name="Usermode" value="Admin">
                <label for="Admin">Admin</label><br>
                <input type="radio" id="Employee" name="Usermode" value="Employee">
                <label for="Employee">Employee</label><br>  
            </div>
            <div>
                <label for="myfile">Upload image</label>
                <input type="file" id="myfile" name="Image">
            </div>
            
            
            
            
            <div class="mt-3">
                <button type="submit" class="btn btn-primary"> Submit </button>
            </div>

    </form>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> 
    <script>
        // Get the HTML element you want to display
        var content = document.getElementById("alert");

        // Show the content for 5 seconds
        content.style.display = "block";
        setTimeout(function() {
        content.style.display = "none";
        }, 4000);
    </script>
</body>

PayrollManagement/Views/Admin/removeEmployee.cshtml
@model Employee
@{
    Layout = "_Layout";
}
<head>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
   
    <div class="container card">
        <form method="post" class="form-container">
             <div>
                <h1>Remove Employee</h1>
            </div>
            <div class="mb-3 mt-3">
                <label  class="form-label"> Employee ID </label>
                <input asp-for="EmployeeID" name="EmployeeID"class="form-control" value=@ViewBag.employeeID placeholder="Enter employee ID"/>
                <span asp-validation-for="EmployeeID" style="color:rgb(255, 68, 68);"></span>
            </div>   
            <div class="mt-3">
                <button type="submit" class="btn btn-primary"> Delete </button>
                
            </div> 

        </form>
    </div>
</body>

@section Scripts{

    <partial name ="_ValidationScriptsPartial"/>
}

PayrollManagement/Views/Admin/searchEmployee.cshtml
@model Employee
@{
    Layout = "_Layout";
}
<head>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    
<div class="container card">
    <form method="post" class="form-container">
        <div>
            <h1>search Employee</h1>
        </div>
        <div class="mb-3 mt-3">
            <input asp-for="EmployeeID" type="number" name="EmployeeID"class="form-control" placeholder="Enter employee ID"/>
            
        </div>   
         <div class="mt-3">
            <a asp-controller="Admin" asp-action="searchEmployee">
                <button  class="btn btn-primary"> Submit </button>
            </a>
            
        </div>

    </form>
</div>
</body>

@section Scripts{

    <partial name ="_ValidationScriptsPartial"/>
}

PayrollManagement/Views/Admin/status.cshtml
@model Employee
 @{
    if(@ViewBag.result == "Registered"){
        <div>Welcome @ViewBag.name</div>
    }else if (@ViewBag.result == "Deleted"){
        <div>Deleted</div>
    }else if(@ViewBag.update == "Updated"){
        <div>Updated</div>
    }else if(@ViewBag.signup == "signedup"){
        <div>Signed up</div>
    }
    else{
        <div>Fails</div>
    }

    
        
 }
    

PayrollManagement/Views/Admin/updateDetails.cshtml
@using System.Data;
@model System.Data.DataSet; 
@{
    Layout = "_Layout";
}
<head>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <div class="container card">
    @{
        foreach(DataRow row in Model.Tables[0].Rows){
            <form method="post" class="form-container" action="updateDetails">
                <div>
                    <h1> Update details </h1>
                </div>
                <div class="mb-3 mt-3">
                    
                    <input  name="EmployeeID"class="form-control" value=@row[0] placeholder="Enter employee ID"/>
                    
                </div>   

                <div class="mb-3">
                    
                    <input  name="EmployeeName" class="form-control" value=@row[1] placeholder="Enter employee name"/>
                    
                </div> 

                <div class="mb-3">
                    
                    <input name="Age" class="form-control" value=@row[2] placeholder="Enter employee age"/>
                    
                </div> 

                <div class="mb-3">
                    <input  name="Salary" class="form-control" value=@row[3] placeholder="Enter employee salary"/>
                    
                </div> 
                
                <select name="Department" class="form-control" value=@row[4] aria-placeholder="Choose department">
                    <option value="Developement"> Developement </option>
                    <option value="Research"> Research </option>
                    <option value="Testing"> Testing </option>
                </select>  

                <div class="mb-3">
                    <input  name="PhoneNumber"  class="form-control" value=@row[5] placeholder="Enter phone number"/>
                </div>
                <div class="mb-3">
                    <input  name="MailId"  class="form-control" value=@row[6] placeholder="Enter mail id"/>
                    
                <div>
                <div>
                    <input  name="Password"  class="form-control" value=@row[7] placeholder="Enter password"/>
                </div>

                </div>
                <div class="mt-3">
                    <button type="submit" class="btn btn-primary"> Submit </button>
                </div>

            </form>

        }
    }
        
    </div>
</body>

@section Scripts{

    <partial name ="_ValidationScriptsPartial"/>
}

PayrollManagement/Views/Admin/viewAdmin.cshtml
@using System.Data
@model System.Data.DataSet
@{
    Layout = "_Layout";
}
<div class="container text-center">
    <h1>
        View Details
    </h1>
</div>
<table class="table table-striped" style="margin-left:6em">
    <tr>
        
        <th>EMPLOYEE ID</th>
        <th>Empoloyee name</th>
        <th>Employee age</th>
        <th>Employee salary</th>
        <th>Department</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    
    @{
        foreach(DataRow row in Model.Tables[0].Rows)
        {
            <tr>
                <td>@row[0]</td>
                <td>@row[1]</td>
                <td>@row[2]</td>
                <td>@row[3]</td>
                <td>@row[4]</td>
                <td><a href="@Url.Action("removeAdmin", "Admin", new { EmpID = @row[0] })"><button type="submit" class="btn btn-primary"> Delete</button></a></td>
                <td><a href="@Url.Action("updateDetails", "Admin", new { EmpID = @row[0] })"><button type="submit" class="btn btn-outline-primary"> Update</button></a></td>
                <!-- <td><a href="@Url.Action("manageSalary", "Salary", new { EmpID = @row[0] })"><button class="btn btn-outline-danger">Pay</button></a></td> -->
                
            </tr>
            
        }
    }
</table>

PayrollManagement/Views/Admin/viewComplaints.cshtml
@model IEnumerable<ComplaintsModel>
@{
    Layout = "_Layout";
}
<html>
<head>
    <title>View complaints </title>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="~/css/profile.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.css">
    </head>
</head>
<body>
    <table class="table table-striped" style="margin:3em 0 0 6em">
    <tr>
        <th>ID</th>
        <th>Employee ID</th>
        <th>Complaints</th>
  
       
        

    </tr>
    
    @{
        foreach(var data in @Model)
        {
            <tr>
                <td>@data.id</td>
                <td>@data.employeeID</td>
                <td>@data.complaint</td>
                
            </tr>
            
        }
    }
</table>

</body>
</html>

PayrollManagement/Views/Admin/viewEmployee.cshtml
@using System.Data
@model System.Data.DataSet
@{
    Layout = "_Layout";
}
<div class="container text-center">
    <h1>
        Employee Details
    </h1>
</div>
<table class="table table-striped" style="margin-left:6em">
    <tr>
        
        <th>EMPLOYEE ID</th>
        <th>Empoloyee name</th>
        <th>Employee age</th>
        <th>Employee salary</th>
        <th>Department</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    
    @{
        foreach(DataRow row in Model.Tables[0].Rows)
        {
            <tr>
                <td>@row[0]</td>
                <td>@row[1]</td>
                <td>@row[2]</td>
                <td>@row[3]</td>
                <td>@row[4]</td>
                <td><a href="@Url.Action("removeEmployee", "Admin", new { EmpID = @row[0] })"><button type="submit" class="btn btn-primary"> Delete</button></a></td>
                <td><a href="@Url.Action("updateDetails", "Admin", new { EmpID = @row[0] })"><button type="submit" class="btn btn-outline-primary"> Update</button></a></td>
                <td><a href="@Url.Action("manageSalary", "Salary", new { EmpID = @row[0] })"><button class="btn btn-outline-danger">Pay</button></a></td>
            </tr>
            
        }
    }
</table>